### ISSUE TITLE
Outlander PHEV bigger battery capacity: 40 kWh

### ISSUE THREAD

**Issue by pert-sa** [tomdebree/OutlanderPHEVBMS#1]
I have installed new batteries of 40 kWh/80 x 135 Ah on my Outlander PHEV (2014). Now the original BMU does not understand bigger capacity, so operation distance is still 45 km. Is it possible to buy SimpBMS programmed for bigger battery capacity?

**Comment by pvojnisek** [comment]
@pert-sa would you please share some information about your battery upgrade? (cell type, placement, etc..)

**Comment by pert-sa** [comment]
This is a big project. The battery compartment must be enlarged and the cell cooling system removed. More space needs to be made in the chassis of the car. The CMU wiring harness must be replaced. Here in Northern Europe, batteries do not need cooling. In warm conditions, batteries need cooling. Quick charge also requires cooling
